-- Initial schema for NearPoint.
-- Mirrors the columns Hibernate previously generated from the Place entity
-- (default CamelCaseToUnderscoresNamingStrategy) so `ddl-auto=validate` passes.
CREATE TABLE places (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id            VARCHAR(255),
    name                VARCHAR(255),
    vicinity            VARCHAR(1000),
    latitude            FLOAT8,
    longitude           FLOAT8,
    types               VARCHAR(1000),
    rating              FLOAT8,
    user_ratings_total  INTEGER,
    photo_reference     VARCHAR(1000),
    search_latitude     FLOAT8,
    search_longitude    FLOAT8,
    search_radius       INTEGER,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6)
);
