CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(255),
    created_at    TIMESTAMP(6)
);

CREATE TABLE user_favorites (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    place_id           VARCHAR(255) NOT NULL,
    name               VARCHAR(255),
    vicinity           VARCHAR(1000),
    latitude           FLOAT8,
    longitude          FLOAT8,
    types              VARCHAR(1000),
    rating             FLOAT8,
    user_ratings_total INTEGER,
    photo_reference    VARCHAR(1000),
    price_level        VARCHAR(255),
    open_now           BOOLEAN,
    created_at         TIMESTAMP(6),
    CONSTRAINT uq_user_place UNIQUE (user_id, place_id)
);

CREATE INDEX idx_user_favorites_user ON user_favorites (user_id);
