CREATE TABLE push_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint   VARCHAR(1000) NOT NULL UNIQUE,
    p256dh     VARCHAR(255) NOT NULL,
    auth       VARCHAR(255) NOT NULL,
    user_id    BIGINT,
    created_at TIMESTAMP(6)
);

CREATE INDEX idx_push_user ON push_subscriptions (user_id);
