CREATE TABLE shared_lists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(16) NOT NULL UNIQUE,
    name       VARCHAR(255),
    kind       VARCHAR(20),
    payload    TEXT NOT NULL,
    user_id    BIGINT,
    created_at TIMESTAMP(6)
);
