CREATE TABLE poll_votes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(16) NOT NULL,
    place_id   VARCHAR(255) NOT NULL,
    voter      VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT uq_poll_voter UNIQUE (slug, voter)
);

CREATE INDEX idx_poll_slug ON poll_votes (slug);
